### ISSUE TITLE
Please update the json-schema gem

### ISSUE THREAD

**Issue by saiqulhaq** [ceritium/render_editorjs#18]
latest json schema gem version is 4
can we update this gem dependency to be 3 at least?
it works https://github.com/ceritium/render_editorjs/compare/master...saiqulhaq:render_editorjs:master
all rake test passed

**Comment by ceritium** [comment]
Hi @saiqulhaq, many thanks!

Would you like to open a proper MR? In any case, maybe I could do it this evening.

**Comment by ceritium** [comment]
Hi @saiqulhaq done in https://github.com/ceritium/render_editorjs/pull/20 and I already released a new version.
